version: '3.7'

services:
  php:
    build: '.'
    container_name: laravel-php
    depends_on:
      - composer_installation
    networks:
      - backend
    volumes:
      - ./html:/var/www/html
      - ./apache2/log:/var/log/apache2

  apache:
    build: './apache2/'
    container_name: laravel-apache
    depends_on:
      - php
      - pgsql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./apache2/log:/var/log/apache2

  pgsql:
    image: postgres:12.0-alpine
    container_name: laravel-pgsql
    working_dir: /data/pgsql
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
      - ./html/database/legacy:/var/lib/postgresql
    environment:
      POSTGRES_USER: pguser
      PGPASSWORD: pgpwd
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432
    networks:
      - backend

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./html/:/app
    command: sh -c "composer install --ignore-platform-reqs && cp .env.example .env && php artisan key:generate"

  node:
    image: node
    working_dir: /usr/app
    user: node
    environment:
      NPM_CONFIG_PREFIX: /home/node/.npm-global
      PATH: $PATH:/home/node/.npm-global/bin
    networks:
      - frontend
    volumes:
      - ./html/:/usr/app
    command: sh -c "npm install -g cross-env && npm install"

networks:
  frontend:
  backend:
