name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: T
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PHRASE }}
          script: |
             cd /var/www/html/siiip
             git pull
             cd html
             composer install --optimize-autoloader --no-dev
             php artisan config:cache && php artisan route:cache && php artisan optimize:clear
             npm i
             export NODE_ENV=production && node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js